#!/bin/bash

echo "Installing TFSwitch"
wget -N -c https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
chmod 755 install.sh

# Install TFSwitch in a location you have permission
./install.sh -b $(pwd)/.bin

# Set path to executable
TFSWITCH_PATH=$(pwd)/.bin
export PATH=$TFSWITCH_PATH:$PATH

$TFSWITCH_PATH/tfswitch -b $TFSWITCH_PATH/terraform

terraform "$@"